# **Numpy: Arrays and Matrices**

## NumPy is an extension to the Python Programming language, adding support for large,
## multi-dimensional arrays and with a large-level of mathematical functions to operate
## on those arrays. NumPy is having the full form "Numeric Python".

In [1]:
# importing required module
import numpy as np

## **Create arrays**

In [6]:
# creating ndarrays from lists
# note: in one ndarray, all data will have same datatype. (And will be converted if required)
data1 = [100, 300, 200, False, 400, True, 500]
print (data1, len(data1), type(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1))

[100, 300, 200, False, 400, True, 500] 7 <class 'list'>
[100 300 200   0 400   1 500] 7 <class 'numpy.ndarray'>


In [8]:
data1 = [100, 300, 200.5, 400, True, False, 500]
print (data1, len(data1), type(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1))

[100, 300, 200.5, 400, True, False, 500] 7 <class 'list'>
[100.  300.  200.5 400.    1.    0.  500. ] 7 <class 'numpy.ndarray'>


In [9]:
data1 = [100, 300, 200.5, "400", True, False, 500]
print (data1, len(data1), type(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1))

[100, 300, 200.5, '400', True, False, 500] 7 <class 'list'>
['100' '300' '200.5' '400' 'True' 'False' '500'] 7 <class 'numpy.ndarray'>


In [10]:
print (list(range(1, 10)))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
data1 = [10, 20, 30, 40, 50, 60, 70, 80]
print (data1, len(data1), type(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1))

[10, 20, 30, 40, 50, 60, 70, 80] 8 <class 'list'>
[10 20 30 40 50 60 70 80] 8 <class 'numpy.ndarray'>


In [14]:
print (list([range(1, 5), range(5, 9)]))   # list of lists
# data2 = list([range(1, 5), range(5, 9)])
data2 = [[1, 2 , 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(data2, type(data2))
print (arr2, type(arr2))

[range(1, 5), range(5, 9)]
[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [17]:
for x in np.nditer(arr2):
    print (x, end = ", ")

1, 2, 3, 4, 5, 6, 7, 8, 

In [25]:
print (arr1, arr1.shape, type(arr1))
print (arr2, arr2.shape, type(arr2))
data1 = arr1.tolist()
print (data1, type(data1))
data2 = arr2.tolist()
print (data2, type(data2))

[10 20 30 40 50 60 70 80] (8,) <class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]] (2, 4) <class 'numpy.ndarray'>
[10, 20, 30, 40, 50, 60, 70, 80] <class 'list'>
[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>
