# **Numpy: Arrays and Matrices**

## NumPy is an extension to the Python Programming language, adding support for large,
## multi-dimensional arrays and with a large-level of mathematical functions to operate
## on those arrays. NumPy is having the full form "Numeric Python".

In [1]:
# importing required module
import numpy as np

## **Create arrays**

In [6]:
# creating ndarrays from lists
# note: in one ndarray, all data will have same datatype. (And will be converted if required)
data1 = [100, 300, 200, False, 400, True, 500]
print (data1, len(data1), type(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1))

[100, 300, 200, False, 400, True, 500] 7 <class 'list'>
[100 300 200   0 400   1 500] 7 <class 'numpy.ndarray'>


In [8]:
data1 = [100, 300, 200.5, 400, True, False, 500]
print (data1, len(data1), type(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1))

[100, 300, 200.5, 400, True, False, 500] 7 <class 'list'>
[100.  300.  200.5 400.    1.    0.  500. ] 7 <class 'numpy.ndarray'>


In [9]:
data1 = [100, 300, 200.5, "400", True, False, 500]
print (data1, len(data1), type(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1))

[100, 300, 200.5, '400', True, False, 500] 7 <class 'list'>
['100' '300' '200.5' '400' 'True' 'False' '500'] 7 <class 'numpy.ndarray'>


In [10]:
print (list(range(1, 10)))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [11]:
data1 = [10, 20, 30, 40, 50, 60, 70, 80]
print (data1, len(data1), type(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), type(arr1))

[10, 20, 30, 40, 50, 60, 70, 80] 8 <class 'list'>
[10 20 30 40 50 60 70 80] 8 <class 'numpy.ndarray'>


In [14]:
print (list([range(1, 5), range(5, 9)]))   # list of lists
# data2 = list([range(1, 5), range(5, 9)])
data2 = [[1, 2 , 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(data2, type(data2))
print (arr2, type(arr2))

[range(1, 5), range(5, 9)]
[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [17]:
for x in np.nditer(arr2):
    print (x, end = ", ")

1, 2, 3, 4, 5, 6, 7, 8, 

In [25]:
print (arr1, arr1.shape, type(arr1))
print (arr2, arr2.shape, type(arr2))
data1 = arr1.tolist()
print (data1, type(data1))
data2 = arr2.tolist()
print (data2, type(data2))

[10 20 30 40 50 60 70 80] (8,) <class 'numpy.ndarray'>
[[1 2 3 4]
 [5 6 7 8]] (2, 4) <class 'numpy.ndarray'>
[10, 20, 30, 40, 50, 60, 70, 80] <class 'list'>
[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>


In [31]:
print (arr1, type(arr1))
print (len(arr1), arr1.shape, arr1.ndim, arr1.size, arr1.dtype)
print (arr2, type(arr2))
print (len(arr2), arr2.shape, arr2.ndim, arr2.size, arr2.dtype)

[10 20 30 40 50 60 70 80] <class 'numpy.ndarray'>
8 (8,) 1 8 int32
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>
2 (2, 4) 2 8 int32


In [30]:
var1 = (8)
print (var1, type(var1))
var1 = (8,) # singleton representation of a tuple
print (var1, type(var1))

8 <class 'int'>
(8,) <class 'tuple'>


## **Creating Special Arrays**

In [40]:
print (np.zeros(10))
print (np.zeros(10).astype(int))
print (np.zeros((2, 5)))
print (np.zeros((2, 5)).astype(int))
print (np.zeros(10).reshape(2, 5))
print (np.zeros(10).reshape(5, 2).astype(int))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0 0 0 0]
 [0 0 0 0 0]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [42]:
arr3 = np.zeros(10).reshape(2, 5).astype(int)
print (arr3)
arr3 = arr3.astype(float)
print (arr3)

[[0 0 0 0 0]
 [0 0 0 0 0]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [57]:
arr3 = np.array(range(10)).reshape(5, 2)
print (arr3, arr3.shape)
arr3 = np.arange(10).reshape(5, 2)
print (arr3, arr3.shape)
print (arr3.T)
print (arr3.transpose())

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] (5, 2)
[[0 2 4 6 8]
 [1 3 5 7 9]]
[[0 2 4 6 8]
 [1 3 5 7 9]]


In [58]:
print (np.ones(10))
print (np.ones(10).astype(int))
print (np.ones((2, 5)))
print (np.ones((2, 5)).astype(int))
print (np.ones(10).reshape(2, 5))
print (np.ones(10).reshape(5, 2).astype(int))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [60]:
print (np.ones(10))
print (np.ones(10) * 7)
print (np.zeros(10))
print (np.zeros(10) + 7)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]


In [63]:
arr2 = np.arange(12).reshape(3, 4)
print (arr2)
print (arr2.flatten())
print(arr2.T.flatten())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  4  8  1  5  9  2  6 10  3  7 11]


In [67]:
matrix = np.arange(10, dtype = float).reshape((2, 5))
print (matrix)
print("Stored in C-style order (Row Major):")
cmatrix = matrix.copy(order = 'C')
print (cmatrix)
for x in np.nditer(cmatrix):
    print (x, end = ", ")

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
Stored in C-style order (Row Major):
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 

In [68]:
print("Stored in F-style order (Column Major):")
fmatrix = matrix.copy(order = 'F')
print (fmatrix)
for x in np.nditer(fmatrix):
    print (x, end = ", ")

Stored in F-style order (Column Major):
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
0.0, 5.0, 1.0, 6.0, 2.0, 7.0, 3.0, 8.0, 4.0, 9.0, 

## **Append, Insert, Delete and Sort Operations**

In [79]:
matrix = np.arange(10, dtype = np.int8)
print (matrix, len(matrix))
matrix = np.append(matrix, [10, 11, 12])
print (matrix, len(matrix))
matrix = np.insert(matrix, 3, [13, 14, 15])
print (matrix, len(matrix))
matrix = np.delete(matrix, [5, 6, 7])
print (matrix)
matrix = np.sort(matrix)
print (matrix)
print (-matrix)
matrix = -np.sort(-matrix)
print (matrix)

[0 1 2 3 4 5 6 7 8 9] 10
[ 0  1  2  3  4  5  6  7  8  9 10 11 12] 13
[ 0  1  2 13 14 15  3  4  5  6  7  8  9 10 11 12] 16
[ 0  1  2 13 14  5  6  7  8  9 10 11 12]
[ 0  1  2  5  6  7  8  9 10 11 12 13 14]
[  0  -1  -2  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14]
[14 13 12 11 10  9  8  7  6  5  2  1  0]


## **Concatenate and Stack of Two Arrays**

In [84]:
a = np.array([[1, 2], [3, 4]])
print ("First Array:")
print (a)
b = np.array([[5, 6], [7, 8]])
print ("Second Array:")
print (b)
# both the arrays are of the same dimensions
print ("Joining these two arrays along axis 0")
print (np.concatenate((a, b)))
print ("Joining these two arrays along axis 1")
print (np.concatenate((a, b), axis = 1))

First Array:
[[1 2]
 [3 4]]
Second Array:
[[5 6]
 [7 8]]
Joining these two arrays along axis 0
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Joining these two arrays along axis 1
[[1 2 5 6]
 [3 4 7 8]]


In [88]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print ("First Array:")
print (a)
b = np.array([[5, 6], [7, 8], [9, 10]])
print ("Second Array:")
print (b)
# both the arrays are not of the same dimensions
print ("Joining these two arrays along axis 1")
print (np.concatenate((a, b), axis = 1))

First Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Array:
[[ 5  6]
 [ 7  8]
 [ 9 10]]
Joining these two arrays along axis 1
[[ 1  2  3  5  6]
 [ 4  5  6  7  8]
 [ 7  8  9  9 10]]


In [101]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print (a, a.shape, a.ndim)
a = a.reshape(1, -1)
print (a, a.shape, a.ndim)
a = a.reshape(1, 1, -1)
print (a, a.shape, a.ndim)
a = a.reshape(1, -1)
print (a, a.shape, a.ndim)
a = a.reshape(-1)
print (a, a.shape, a.ndim)

[10 20 30 40 50 60 70 80] (8,) 1
[[10 20 30 40 50 60 70 80]] (1, 8) 2
[[[10 20 30 40 50 60 70 80]]] (1, 1, 8) 3
[[10 20 30 40 50 60 70 80]] (1, 8) 2
[10 20 30 40 50 60 70 80] (8,) 1


In [104]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print (a, a.shape, a.ndim)
a = a.reshape(2, -1, 2)
print (a, a.shape, a.ndim)

[10 20 30 40 50 60 70 80] (8,) 1
[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]] (2, 2, 2) 3


## **Selection**

In [114]:
#                 0   1   2   3   4   5   6   7   8
arr1 = np.array([11, 82, 53, 94, 15, 26, 57, 98, 69])
#                -9  -8  -7  -6  -5  -4  -3  -2  -1
print (arr1, len(arr1))
print (arr1[2], arr1[4], arr1[-6], arr1[-3], arr1[7], arr1[-2])  # indexing
print (arr1[3:7], arr1[-6:-2], arr1[3:-2], arr1[-6:7])           # slicing
print (arr1[3:], arr1[-6:])
print (arr1[:6], arr1[:-3])
print (arr1[::-1])
print (arr1[::2], arr1[1::2])

[11 82 53 94 15 26 57 98 69] 9
53 15 94 57 98 98
[94 15 26 57] [94 15 26 57] [94 15 26 57] [94 15 26 57]
[94 15 26 57 98 69] [94 15 26 57 98 69]
[11 82 53 94 15 26] [11 82 53 94 15 26]
[69 98 57 26 15 94 53 82 11]
[11 53 15 57 69] [82 94 26 98]


## **Views and Copies**

In [123]:
arr = np.arange(10)
print (arr, arr[5:8])
arr[5:8] = 20
print (arr)
arr_view = arr[5: 8]
print (arr_view)
arr_view[:] = 90
print (arr_view, arr, type(arr_view))

[0 1 2 3 4 5 6 7 8 9] [5 6 7]
[ 0  1  2  3  4 20 20 20  8  9]
[20 20 20]
[90 90 90] [ 0  1  2  3  4 90 90 90  8  9] <class 'numpy.ndarray'>


In [124]:
arr = np.arange(10)
print (arr, arr[5:8])
arr[5:8] = 20
print (arr)
arr_copy = arr[5: 8].copy()
print (arr_copy)
arr_copy[:] = 90
print (arr_copy, arr, type(arr_copy))

[0 1 2 3 4 5 6 7 8 9] [5 6 7]
[ 0  1  2  3  4 20 20 20  8  9]
[20 20 20]
[90 90 90] [ 0  1  2  3  4 20 20 20  8  9] <class 'numpy.ndarray'>


## **Using Boolean Arrays**