# **Introduction to Pandas**
* **It is often said that 80% of data analysis activity is spent on the data cleaning and preparation of our data. To get the grip over this activity, this section will focus on a small but important aspect of data manipulation and cleaning with Pandas.**

## **Inbuilt Data Structure in Pandas**
**There are two types of data structures are there in Pandas -**
* **Series -** It is one-dimensional labeled array capable of holding any data type (integer, string, float, Python objects etc.) of data. The axis is collectively referred to as index.
* **Data Frame -** It is a two-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL Table or a Series of objects

In [1]:
# importing all required modules
import pandas as pd
import numpy as np

## **Series Data Structure**
**pandas.core.series.Series(data, index, dtype, copy)**
* **data -** data takes various forms like ndarray, list, constants, dictionary etc.
* **index -** it is unique and hashable for easy identification.
* **dtype -** it is for data type.
* **copy -** copy data, and its default value is False. It only affects for Series or one dimensional ndarray inputs.

In [3]:
# creating empty Series
s = pd.Series()
print (s, type(s))

Series([], dtype: object) <class 'pandas.core.series.Series'>


In [9]:
arr_data = np.array([100, 200, 400, 500, 300])
print (arr_data)
s = pd.Series(data = arr_data, copy = False)
print (s)
s[2] = 999
arr_data[3] = 888
print (arr_data)
print (s)

[100 200 400 500 300]
0    100
1    200
2    400
3    500
4    300
dtype: int32
[100 200 999 888 300]
0    100
1    200
2    999
3    888
4    300
dtype: int32


In [7]:
arr_data = np.array([100, 200, 400, 500, 300])
print (arr_data)
s = pd.Series(data = arr_data, copy = True)
print (s)
s[2] = 999
arr_data[3] = 888
print (arr_data)
print (s)

[100 200 400 500 300]
0    100
1    200
2    400
3    500
4    300
dtype: int32
[100 200 400 888 300]
0    100
1    200
2    999
3    500
4    300
dtype: int32
