# **Introduction to Pandas**
* **It is often said that 80% of data analysis activity is spent on the data cleaning and preparation of our data. To get the grip over this activity, this section will focus on a small but important aspect of data manipulation and cleaning with Pandas.**

## **Inbuilt Data Structure in Pandas**
**There are two types of data structures are there in Pandas -**
* **Series -** It is one-dimensional labeled array capable of holding any data type (integer, string, float, Python objects etc.) of data. The axis is collectively referred to as index.
* **Data Frame -** It is a two-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL Table or a Series of objects

In [1]:
# importing all required modules
import pandas as pd
import numpy as np

## **Series Data Structure**
**pandas.core.series.Series(data, index, dtype, copy)**
* **data -** data takes various forms like ndarray, list, constants, dictionary etc.
* **index -** it is unique and hashable for easy identification.
* **dtype -** it is for data type.
* **copy -** copy data, and its default value is False. It only affects for Series or one dimensional ndarray inputs.

In [3]:
# creating empty Series
s = pd.Series()
print (s, type(s))

Series([], dtype: object) <class 'pandas.core.series.Series'>


In [9]:
arr_data = np.array([100, 200, 400, 500, 300])
print (arr_data)
s = pd.Series(data = arr_data, copy = False)
print (s)
s[2] = 999
arr_data[3] = 888
print (arr_data)
print (s)

[100 200 400 500 300]
0    100
1    200
2    400
3    500
4    300
dtype: int32
[100 200 999 888 300]
0    100
1    200
2    999
3    888
4    300
dtype: int32


In [7]:
arr_data = np.array([100, 200, 400, 500, 300])
print (arr_data)
s = pd.Series(data = arr_data, copy = True)
print (s)
s[2] = 999
arr_data[3] = 888
print (arr_data)
print (s)

[100 200 400 500 300]
0    100
1    200
2    400
3    500
4    300
dtype: int32
[100 200 400 888 300]
0    100
1    200
2    999
3    500
4    300
dtype: int32


In [12]:
arr_data = np.array(['apple', 'banana', 'cherry', 'pineapple'])
print (arr_data, len(arr_data))
s = pd.Series(data = arr_data)
print (s)
print (s[0], s[2])

['apple' 'banana' 'cherry' 'pineapple'] 4
0        apple
1       banana
2       cherry
3    pineapple
dtype: object
apple cherry


In [31]:
arr_data = np.array(['apple', 'banana', 'cherry', 'pineapple'])
print (arr_data, len(arr_data))
s = pd.Series(data = arr_data, index = [100, 103, 101, 103])
print (s)
print (s[100], type(s[100]))
print (s[103], type(s[103]))

['apple' 'banana' 'cherry' 'pineapple'] 4
100        apple
103       banana
101       cherry
103    pineapple
dtype: object
apple <class 'str'>
103       banana
103    pineapple
dtype: object <class 'pandas.core.series.Series'>


In [23]:
arr_data = np.array(['apple', 'banana', 'cherry', 'pineapple'])
print (arr_data, len(arr_data))
s = pd.Series(data = arr_data, index = [100, 103, 100, 103])
print (s)
print (s[100])
print (s[103])

['apple' 'banana' 'cherry' 'pineapple'] 4
100        apple
103       banana
100       cherry
103    pineapple
dtype: object
100     apple
100    cherry
dtype: object
103       banana
103    pineapple
dtype: object


In [24]:
import warnings
warnings.filterwarnings('ignore')

In [26]:
arr_data = np.array(['apple', 'banana', 'cherry', 'pineapple'])
print (arr_data, len(arr_data))
s = pd.Series(data = arr_data, index = ['fruit-1', 'fruit-2', 'fruit-3', 'fruit-4'])
print (s)
print (s['fruit-1'], s[0])
print (s['fruit-3'], s[2])

['apple' 'banana' 'cherry' 'pineapple'] 4
fruit-1        apple
fruit-2       banana
fruit-3       cherry
fruit-4    pineapple
dtype: object
apple apple
cherry cherry


In [28]:
# create a Series from a dictionary
dict_data = {'apple':104, 'banana':306, 'pineapple': '455', 'coconut':897}
print (dict_data, len(dict_data))
s = pd.Series(dict_data)
print (s)

{'apple': 104, 'banana': 306, 'pineapple': '455', 'coconut': 897} 4
apple        104
banana       306
pineapple    455
coconut      897
dtype: object


In [29]:
dict_data = {'apple':104, 'banana':306, 'pineapple': '455', 'coconut':897}
print (dict_data, len(dict_data))
s = pd.Series(dict_data, index = ['pineapple', 'apple', 'cherry', 'apple', 'coconut', 'mango'])
print (s)

{'apple': 104, 'banana': 306, 'pineapple': '455', 'coconut': 897} 4
pineapple    455
apple        104
cherry       NaN
apple        104
coconut      897
mango        NaN
dtype: object


In [34]:
# create a Series from a scalar
s = pd.Series(50, index = [0, 1, 2, 3, 4, 5])
print (s)
s = pd.Series(60, index = [0, 2, 1, 3, 2, 3])
print (s)

0    50
1    50
2    50
3    50
4    50
5    50
dtype: int64
0    60
2    60
1    60
3    60
2    60
3    60
dtype: int64


In [38]:
# create a Series from a list
s = pd.Series(data = [101, 103, 102, 105, 104], index = ('red', 'blue', 'brown', 'black', 'white'))
print (s)
print (s['blue'], s[1])
print (s.sort_index())
print (s.sort_values())
print (s.argmax(), s.argmin())
print (s.count())

red      101
blue     103
brown    102
black    105
white    104
dtype: int64
103 103
black    105
blue     103
brown    102
red      101
white    104
dtype: int64
red      101
brown    102
blue     103
white    104
black    105
dtype: int64
3 0
5
